version: "3.9"

services:
  php:
    build: .
    ports:
      - "9501-9509:9501-9509"
    volumes:
      - ./php/conf:/usr/local/etc/php
      - ./apps:/var/www
    depends_on:
      - mysql
      - redis
    environment:
      PHP_IDE_CONFIG: "serverName=swoole"
    command: tail -F anything

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql

  redis:
    ports:
      - "6379:6379"
    image: redis:alpine

  elasticsearch:
    image: elasticsearch:7.17.0
    ports:
      - "9200:9200"